/*
 * EASYQUESTION
 * EASYQUESTINO
 * EASYQUESTINO
 * EASYQUESITNO
 * EASYQUEISTNO
 * EASYQUEISTNO
 * EASYQEUISTNO
 * EASYEQUISTNO
 * EASEYQUISTNO
 * EAESYQUISTNO
 * EAESYQUISTNO
 * AEESYQUISTNO
 *
 * ** end inital compexch **
 *
 * AEESYQUISTNO
 * AEESYQUISTNO
 * AEESYQUISTNO
 * AEESYQUISTNO 5
 * AEESQYUISTNO
 * AEEQSYUISTNO
 * AEEQSYUISTNO 6
 * AEEQSUYISTNO
 * AEEQSUYISTNO 7
 * AEEQSUIYSTNO
 * AEEQSIUYSTNO
 * AEEQISUYSTNO
 * AEEIQSUYSTNO
 * AEEIQSUYSTNO 8
 * AEEIQSUSYTNO
 * AEEIQSSUYTNO
 * AEEIQSSUYTNO 9
 * AEEIQSSUTYNO
 * AEEIQSSTUYNO
 * AEEIQSSTUYNO 10
 * AEEIQSSTUNYO
 * AEEIQSSTNUYO
 * AEEIQSSNTUYO
 * AEEIQSNSTUYO
 * AEEIQNSSTUYO
 * AEEINQSSTUYO
 * AEEINQSSTUYO 11
 * AEEINQSSTUOY
 * AEEINQSSTOUY
 * AEEINQSSOTUY
 * AEEINQSOSTUY
 * AEEINQOSSTUY
 * AEEINOQSSTUY
 */